Repository iadvize/boxed-tag, pull requests merged in 2023-05, with the labels that each got.

#17 refact: rename iadvize internals
  @types/window.d.ts
  CHANGELOG.md
  README.md
  example/webSdkMethods.js
  src/host.test.ts
  src/host.ts
Labels: patch

#18 feat: add activate token refresh
  CHANGELOG.md
  README.md
  example/webSdkMethods.js
  jest.config.js
  src/host.test.ts
  src/iframe.ts
Labels: minor

#19 Rename "sandboxed" variables
  .github/workflows/on-merge.yml
  @types/window.d.ts
  CHANGELOG.md
  README.md
  example/host.js
  example/iframe.html
  example/iframe.js
  example/index.html
  example/webSdkMethods.js
  package-lock.json
  package.json
  src/host.test.ts
  src/host.ts
  src/iframe.html
Labels: major

#21 fix: ci changelog
  .github/workflows/on-merge.yml
  CHANGELOG.md
Labels: minor

#22 fix: readme + ci changelog
  .github/workflows/on-merge.yml
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
Labels: patch

#25 feat: Bundle for <script>
  .gitignore
  CHANGELOG.md
  package-lock.json
  package.json
  rollup.config.js
  src/host.ts
  src/iframe.ts
Labels: minor

#26 doc: update communication introduction
  CHANGELOG.md
  README.md
Labels: minor

#27 Upload bundled assets to S3
  .circleci/config.yml
  .circleci/uploadS3.sh
  .github/workflows/ci.yml
  CHANGELOG.md
  package.json
  rollup.config.js
  src/host.ts
  src/iframe.ts
Labels: minor

#28 fix(CI): Fix uploading after a release
  .circleci/config.yml
  CHANGELOG.md
Labels: patch

#29 doc: update iframe sandbox params
  CHANGELOG.md
  README.md
  example/index.html
  example/webSdkMethods.js
Labels: minor

#30 resizeIframe left position condition
  CHANGELOG.md
  package-lock.json
  src/host.test.ts
  src/host.ts
Labels: patch
